import re

translations = {
    "  Reiniciar Agora": "  Reboot Now",
    " Atualizar Agora ": " Update Now ",
    " Pular ": " Skip ",
    "%1 etapa(s) encontraram erros. Verifique o log abaixo.": "%1 step(s) encountered errors. Check the log below.",
    "(O console DNF emitirá a stream aqui assim que o passo iniciar...)": "(The DNF console will feed the stream here as the step starts...)",
    "(Sem detalhes disponíveis)": "(No details available)",
    "<b style='color:#ff6b6b;'>Etapas com Erro</b>": "<b style='color:#ff6b6b;'>Steps with Errors</b>",
    "<b>Ajustes do Sistema</b>": "<b>System Tweaks</b>",
    "<b>Atenção:</b> Os repositórios do RPM Fusion parecem estar ausentes. Volte na Etapa de Repositórios e certifique-se de habilitá-los, ou essas instalações de Codecs irão falhar silenciosamente.": "<b>Attention:</b> RPM Fusion repositories seem missing. Go back to Repositories and ensure they are enabled.",
    "<b>Auditoria de Armazenamento OK</b><br>Carga Baixada: ~%1 GB &nbsp;|&nbsp; Espaço Livre: %2 GB": "<b>Storage Audit OK</b><br>Download Load: ~%1 GB &nbsp;|&nbsp; Free Space: %2 GB",
    "<b>Ferramentas do Sistema & Utilitários</b>": "<b>System Tools & Utilities</b>",
    "<b>Paciência é uma virtude! ⏳</b>": "<b>Patience is a virtue! ⏳</b>",
    "<b>Pacotes Nativos do Sistema (RPM)</b>": "<b>Native System Packages (RPM)</b>",
    "<b>Tamanho Estimado do Pacote: ~%1 GB</b><br>Não foi possível aferir o espaço alocado no disco físico.": "<b>Estimated Size: ~%1 GB</b><br>Unable to measure physical disk space.",
    "<b>⚠️ Espaço Crítico Insuficiente</b><br>Requeridos: <b>~%1 GB</b> &nbsp;|&nbsp; Disponíveis: <b>%2 GB</b>": "<b>⚠️ Insufficient Critical Space</b><br>Required: <b>~%1 GB</b> &nbsp;|&nbsp; Available: <b>%2 GB</b>",
    "<br><br><font color='#ff5555'><b>Ignorando Auditoria: Prosseguindo instalação de forma insegura.</b></font>": "<br><br><font color='#ff5555'><b>Ignoring Audit: Proceeding unsafely.</b></font>",
    "<font color='#4cd14c'><b>[OK] Suporte de hardware VT-x/AMD-V habilitado na BIOS.</b></font><br>": "<font color='#4cd14c'><b>[OK] VT-x/AMD-V hardware support enabled in BIOS.</b></font><br>",
    "<font color='#ff5555'><b>[FALHA] A Virtualização está DESABILITADA na BIOS ou seu CPU não suporta!</b> As Máquinas Virtuais não poderão iniciar até você corrigir isto, mesmo que instale os pacotes.</font><br><br>": "<font color='#ff5555'><b>[FAILURE] Virtualization is DISABLED in BIOS.</b> VMs won't start until fixed.</font><br><br>",
    "<i>Itens não selecionados permanecerão inalterados pelo sistema.</i>": "<i>Unselected items will remain unchanged.</i>",
    "<i>Nada selecionado além das ferramentas base.<br>Retorne e selecione itens para construir seu sistema.</i>": "<i>Nothing selected besides base tools.<br>Return and select items to build your system.</i>",
    "<i>Negociando com servidores online... Baixando via <tt>dnf upgrade --refresh</tt>.</i>": "<i>Negotiating with servers... Downloading via <tt>dnf upgrade --refresh</tt>.</i>",
    "<i>Os seguintes softwares serão empacotados pela plataforma <b>Flatpak via Flathub</b> em caixas de areia blindadas. Nosso instalador conectará e criará as rotas de Flathub automaticamente por você caso não estejam configuradas no sistema.</i>": "<i>The following software will be packaged by <b>Flatpak via Flathub</b> in shielded sandboxes.</i>",
    "<i>Validando ramificações de Kernel do Fedora antes do procedimento...</i>": "<i>Validating Fedora Kernel branches...</i>",
    "<span style='color:#3db03d;'>✓ Integrações validadas e Sistema Atualizado de ponta a ponta com sucesso.</span>": "<span style='color:#3db03d;'>✓ System Updated end-to-end successfully.</span>",
    "<span style='color:#cc7700;'>⚠ Execução pulada pelo usuário. Prossiga sob sua própria responsabilidade.</span>": "<span style='color:#cc7700;'>⚠ Execution skipped by user. Proceed at your own risk.</span>",
    "A interface gráfica necessária para configurar a fonte, cor e posicionamento do MangoHud sem precisar encostar em arquivos de texto.": "The GUI needed to configure your MangoHud without touching text files.",
    "Acelerador Gráfico NVIDIA detectado na barramento físico!": "NVIDIA Graphics Accelerator detected on the physical bus!",
    "Aceleração Gráfica": "Graphics Acceleration",
    "Aceleração Gráfica e GPU": "Graphics Acceleration and GPU",
    "Aguardando inicialização do despachante...": "Waiting for dispatcher initialization...",
    "Alternativa fluída do ProtonUp escrita puramente em Vala e GTK4, muito polida para quem prefere designs orgânicos.": "Fluid ProtonUp alternative written in Vala and GTK4, very polished.",
    "Aplicativos criativos base para vídeos, áudio, vetores e design tridimensional.": "Base creative applications for videos, audio, vectors, and 3D design.",
    "Após todas as dezenas de instalações do Rapidora, faz um flush de gigabytes que não seriam mais usados.": "Flushes gigabytes that wouldn't be used anymore after setup.",
    "As operações automáticas foram delegadas aos Workers no background.": "Automatic operations delegated to background Workers.",
    "Atualização de Base": "Base Update",
    "Atualização do Sistema": "System Update",
    "Audacity": "Audacity",
    "BTop": "BTop",
    "Bazaar Center": "Bazaar Center",
    "Bem-vindo ao Rapidora": "Welcome to Rapidora",
    "Blender 3D (Flatpak)": "Blender 3D",
    "Brave Browser": "Brave Browser",
    "Brave Origin Nightly": "Brave Origin Nightly",
    "Camada de tradução de Windows vital para o linux. O Rapidora compilará Wine x64 e x32 automaticamente simultaneamente.": "Vital Windows translation layer. Compiles x64 and x32 simultaneously.",
    "Camadas vitais pesadas e não-livres, injetando suporte robusto retroativo a formatos MP3, leitura de DVDs e muito mais ao Totem e afins.": "Vital heavy non-free layers, injecting robust support for MP3 formats, DVD reading, and more.",
    "Chrome com anabolizantes. Escudos fortes, bloqueio absoluto de anúncios, telemetrias e rastreadores desde o primeiro bip.": "Chrome on steroids. Strong shields, absolute ad-block, and trackers blocked.",
    "Chromium Base": "Chromium Base",
    "Cliente de streaming musical e podcasts oficial da Spotify.": "Official Spotify music streaming client.",
    "Cliente open source focado exclusivamente no Epic Games, GOG e Amazon Prime de forma hiper otimizada.": "Open source client tailored for Epic Games, GOG, and Amazon Prime.",
    "Codecs Nativos": "Native Codecs",
    "Comunicação & Produtividade": "Communication & Productivity",
    "Configuração Concluída": "Setup Completed",
    "Configuração de Inicialização": "Boot Configuration",
    "Configurações Complementares": "Complementary Settings",
    "Confirmação de Reinício": "Reboot Confirmation",
    "Construa de uma nova maneira usando IA. Um ecossistema completo provido pelos repositórios globais da Google de forma nativa.": "Build in a new way using AI. Complete native Google ecosystem.",
    "Construindo o Sistema": "Building the System",
    "Controlador daemon vital que comanda os módulos do hypervisor. Habilitado automaticamente no boot.": "Vital daemon controller for the hypervisor. Enabled automatically at boot.",
    "Controller Support": "Controller Support",
    "Corrigir integração KDE Google": "Fix KDE Google integration",
    "Criação de Conteúdo": "Content Creation",
    "Desabilitar NetworkManager-wait-online": "Disable NetworkManager-wait-online",
    "Desconhecida": "Unknown",
    "Descubra os astros e trace planetas em tempo real direto da sua máquina.": "Discover stars and trace planets in real-time.",
    "Disponibiliza software de código aberto isento das restrições proprietárias mas não unificado no repositório Fedora oficial (Ex: codecs de vídeo ffmpeg, h264, h265, reprodutor nativo VLC Media).": "Provides open source software free of proprietary restrictions not unified in Fedora.",
    "Distrobox": "Distrobox",
    "Driver Proprietário (Código Fechado). Nosso sistema montará o kernel do Akmod-Nvidia utilizando as assinaturas do RPM Fusion NonFree de forma totalmente silenciosa e automática.": "Proprietary Driver. The system will build Akmod-Nvidia silently.",
    "Drivers AMD MESA": "AMD MESA Drivers",
    "Drivers NVIDIA": "NVIDIA Drivers",
    "Ecossistema Gaming": "Gaming Ecosystem",
    "Ecossistema pleno da Google. O Rapidora cuidará de injetar todas as chaves PGP seguras e criar o dnf.repo dinâmico no disco.": "Full Google ecosystem. Handled elegantly and natively.",
    "Encontre complementos incriveis, módulos extras e extensores robustos.": "Find incredible add-ons, extra modules, and robust extenders.",
    "FFmpeg (Core swap)": "FFmpeg (Core swap)",
    "Fastfetch": "Fastfetch",
    "Fechar": "Close",
    "Ferramenta de estúdio de mesa multipista de rápido processamento para manipulação de áudio.": "Fast-processing multipack desktop studio tool for audio.",
    "Ferramenta veloz de informações de host de terminal.": "Fast terminal host information tool.",
    "Ferramentas de Gaming": "Gaming Tools",
    "Ferramentas de Sistema": "System Tools",
    "Ferramentas de chat, ambientes de construção em IA e suíte de edição.": "Chat tools, AI environments, and editing suites.",
    "Ferramentas e Ajustes de Sistema": "System Tools",
    "Ferramentas nativas do kernel KVM/QEMU para execução de Máquinas Virtuais no nível do hardware.": "Native KVM/QEMU kernel tools for running VMs.",
    "Finalizar >>": "Finish >>",
    "Framework de IA (Fedora RPM)": "AI Framework (Fedora RPM)",
    "Framework e Flatpaks": "Framework & Flatpaks",
    "From Fedora Repos": "From Fedora Repos",
    "GIMP": "GIMP",
    "GOverlay": "GOverlay",
    "GStreamer Bad-Free Extras": "GStreamer Bad-Free Extras",
    "GStreamer Ugly Plugins": "GStreamer Ugly Plugins",
    "Game Launchers": "Game Launchers",
    "Google Antigravity": "Google Antigravity",
    "Google Chrome": "Google Chrome",
    "Gráficos Intel Arc/Integrado detectados.": "Intel Arc/Integrated Graphics detected.",
    "Guia das Caixas de Seleção": "Checkbox Guide",
    "HTop": "HTop",
    "Habilite grandes fontes de software de terceiros. O RPM Fusion é um pré-requisito estrito para multimídia avançada, jogos fluídos e pacotes fechados.": "Enable massive third-party software sources like RPM Fusion.",
    "Heroic Games Launcher (Flatpak)": "Heroic Games Launcher",
    "INSTALADO": "INSTALLED",
    "Identifique sua placa de vídeo principal. Isso garantirá os drivers corretos e aceleradores no kernel do Linux e RPM Fusion.": "Identify your main graphics card to ensure proper drivers.",
    "Ignorar Risco e Continuar": "Ignore Risk and Continue",
    "Informações do Sistema": "System Info",
    "Iniciar Instalação": "Start Setup",
    "Inkscape": "Inkscape",
    "Instalado": "Installed",
    "Instalação com Avisos": "Setup completed with Warnings",
    "Intel / Máquina Virtual": "Intel / Virtual Machine",
    "Interface gráfica amigável de desktop para gerenciar redes virtuais e hospedar Máquinas Virtuais em KVM/QEMU.": "Friendly GUI to manage virtual networks and VMs in KVM/QEMU.",
    "Kdenlive": "Kdenlive",
    "Kernel & Escaladores": "Kernel & Scalers",
    "Kernel Modules Extra": "Kernel Modules Extra",
    "Lançador multifacetado de código aberto perfeito para jogos da GOG, EA, Amazon, emuladores variados e binários offline.": "Open-source launcher perfect for GOG, EA, Amazon, and emulators.",
    "LibreWolf (Flatpak)": "LibreWolf",
    "Libvirt API Daemon": "Libvirt API Daemon",
    "Limpeza de DNF Residual": "DNF Residual Cleanup",
    "Log vazio.": "Empty log.",
    "Lutris": "Lutris",
    "Maior loja digital do mundo, nativa com a maravilhosa integração do Valve Proton embutida para abrir games de Windows.": "World's largest digital store natively integrated with Valve Proton.",
    "MangoHud": "MangoHud",
    "Manter os pacotes de base do Fedora atualizados é essencial antes de efetuarmos injeções profundas de novos programas.": "Keeping Fedora's core packages updated is essential.",
    "Mensageiro rápido nativizado para nuvem via API aberta Telegram.": "Fast native cloud messenger via Telegram API.",
    "Monitor de recursos com uma bela UI colorida nos terminas de shell.": "Resource monitor with a beautiful colorful UI.",
    "Multimídia & Codecs": "Multimedia & Codecs",
    "Navegadores": "Web Browsers",
    "Navegadores & Web": "Web & Browsers",
    "Nenhum erro registrado.": "No errors recorded.",
    "Nenhuma GPU dedicada detectada (Fallback / Intel).": "No dedicated GPU detected (Fallback).",
    "Nenhuma categoria selecionada.": "No category selected.",
    "NÃO INSTALADO": "NOT INSTALLED",
    "Não Instalado": "Not Installed",
    "O MSI Afterburner do Linux. Permite travar quadros e injetar métricas completas e belíssimas de GPU/CPU nos seus jogos.": "The MSI Afterburner of Linux. FPS locking and hardware metrics.",
    "O eterno e clássico editor de gráficos raster recheado de recursos para edição de fotos.": "The classic raster graphics editor loaded with photo editing features.",
    "O fluxo STDOUT dos contêineres e logs DNF será alimentado em tempo-real aqui.\\nClique em uma Categoria à esquerda para auditar...": "STDOUT flow containers and DNF logs will feed in real-time here.",
    "OBS Studio": "OBS Studio",
    "OnlyOffice": "OnlyOffice",
    "Otimiza tempo de boot em quase 20s desativando uma service ociosa.": "Optimizes boot time by disabling an idle service.",
    "Overload: Falta %1 MB": "Overload: Missing %1 MB",
    "Padrão ouro da indústria para gravação de tela, composição de cenas e streaming ao vivo.": "Golden industry standard for screen recording and live streaming.",
    "Performance & Monitoring": "Performance & Monitoring",
    "Placa de Vídeo / APU AMD detectada na barramento físico!": "AMD Graphics Card / APU detected!",
    "Placas gráficas híbridas, APUs estritas Intel ou Máquinas Virtuais. O Mesa nativo padrão do Fedora será unicamente o suficiente.": "Hybrid graphics cards, Intel APUs, or VMs. The default Mesa will suffice.",
    "Plano de comissionamento de sistema gerado. Revise todas as automações alocadas abaixo e clique em iniciar.": "System commissioning plan generated. Review automations below.",
    "Plataforma profissional de manipulação de vetores SVG perfeitamente escaláveis.": "Professional SVG vector manipulation platform.",
    "Plataformas, camadas de compatibilidade Windows, overlays de desempenho e suporte a controles.": "Platforms, Windows compatibility layers, and overlays.",
    "Player hiper robusto famoso por conter seus próprios codecs auto-suficientes, abrindo de tudo e um pouco mais sem dependências externas.": "Hyper robust player containing self-sufficient codecs.",
    "Poderosa suíte corporativa, 100% compatível localmente com planilhas e docs Word XSLX.": "Powerful enterprise suite, 100% compatible locally with Word XSLX.",
    "Poderoso editor de vídeo não-linear mantido livre sob o guarda-chuva do projeto KDE.": "Powerful non-linear video editor.",
    "Portais principais da Web. Navegadores de terceiros terão seus repositórios isolados adicionados automaticamente via dnf.": "Main Web portals and third-party browsers.",
    "Portal chave para pacotes comerciais/fechados vitais para certas rotinas do Linux Gamer, autorizando injeção limpa de ferramentas como o App Steam, Drivers proprietários da NVIDIA e componentes corporativos atrelados.": "Key portal for vital commercial packages for gaming.",
    "Privacy-focused (Flatpak from Flathub)": "Privacy-focused",
    "Procedendo e consolidando %1 pacote(s) ou comandos da categoria.": "Proceeding with %1 packages/commands.",
    "Projetado para Power Users. Inúmeras funções densas de customização lateral e divisões de janelas baseadas em Chromium.": "Designed for Power Users. Dense customization features.",
    "Prosseguir de qualquer forma (Sob Próprio Risco)": "Proceed anyway (At Own Risk)",
    "Proteção de sistema via Snapshots incríveis de estado completo via BTRFS.": "System protection via full-state Snapshots.",
    "Proton & Compatibility Tools": "Proton & Compatibility Tools",
    "ProtonPlus (Flatpak)": "ProtonPlus",
    "ProtonUp-Qt (Flatpak)": "ProtonUp-Qt",
    "Protontricks": "Protontricks",
    "Próximo  →": "Next  →",
    "Rapidora": "Rapidora",
    "Rapidora — Selecione o Idioma": "Rapidora — Select Language",
    "Recomendado caso o seu controle (ex: Xbox, DualShock) não seja detectado nativamente. Provém drivers faltantes ao Kernel base.": "Recommended if your controller is not natively detected.",
    "Redes & Comunicação (Flatpaks Isolados)": "Network & Communication",
    "Refaz varredura DNF de instalação no cache local": "Remakes DNF installation scan in local cache",
    "Reiniciar Imediatamente": "Reboot Immediately",
    "Repositórios RPM Fusion": "RPM Fusion Repositories",
    "Repositórios de Software": "Software Repositories",
    "Repositórios do Sistema": "System Repositories",
    "Script automatizado que injeta vcrun, directx ou media foundation dentro de garrafas de jogos específicos da Steam local.": "Automated script that injects dependencies inside Steam bottles.",
    "Se marcado, indica que será baixado e instalado em sua máquina.": "If checked, it will be downloaded and installed.",
    "Se marcado, o pacote garante atualização/reinstalação.": "If checked, it guarantees update/reinstallation.",
    "Seu sistema foi otimizado com sucesso.": "Your system has been successfully optimized.",
    "Spotify App": "Spotify App",
    "Steam": "Steam",
    "Stellarium Planetarium": "Stellarium Planetarium",
    "Sub-instale ArchLinux, Debian e outras distros no mesmo terminal.": "Sub-install ArchLinux, Debian, etc. in the same terminal.",
    "Sub-plugins adicionais de extensão base para leitura em matrizes de players nativos.": "Additional sub-plugins for extension matrix reading.",
    "Sub-virtualização": "Sub-virtualization",
    "Substitui o pacote ffmpeg-free castrado do Fedora pelo pacote original completo contendo todos os codificadores modernos H264 e H265 ativados.": "Replaces ffmpeg-free with fully featured ffmpeg with H264 and H265.",
    "Substitui o provedor de accounts KDE por um script que restabelece com perfeição o login do Google Drive e YouTube nas contas online.": "Fixes KDE online accounts for Google Drive and YouTube.",
    "Sumário Executivo": "Executive Summary",
    "Suporte a vídeo, áudio e codecs. O repositório RPM Fusion é estritamente exigido a seguir.": "Video, audio, and codecs support.",
    "Suíte Open Source Integrada diretamente e ativamente ao Kernel. Instala extensões RADV, Mesa-DRI e Vulkan em massa.": "Installs RADV, Mesa-DRI, and Vulkan extensions en masse.",
    "Suíte líder de mercado, de código aberto para modelagem 3D, animação, rig de texturas e até simulação real-time.": "Open-source suite for 3D modeling, animation, and texture rigging.",
    "Telegram Desktop": "Telegram Desktop",
    "Third-Party (Repo added automatically)": "Third-Party",
    "Timeshift": "Timeshift",
    "Tudo pronto!": "All set!",
    "Tudo pronto! Seu sistema Fedora foi otimizado com sucesso.": "All set! Your Fedora system was optimized successfully.",
    "Um grande fork do Firefox hiper-focado em privacidade absoluta em tempo real. Empacotado sob segurança sandbox do Flathub.": "A major Firefox fork focused on absolute privacy via sandbox.",
    "Usuário: ": "User: ",
    "Utilitário GUI essencial que instala a última versão experimental do Proton-GE, Luxtorpeda e Wine-GE com poucos cliques.": "Essential GUI utility that installs experimental Proton versions.",
    "Utilitário avançado de linha de comando usado para programar criação massificada de VMs de forma automatizada.": "Advanced CLI utility to map automated mass creation of VMs.",
    "Utilitários essenciais de manutenção e otimização da máquina.": "Essential maintenance and optimization machine utilities.",
    "VLC Media Player": "VLC Media Player",
    "Versão do Fedora: ": "Fedora Version: ",
    "Versão Nightly do Brave com repositório origin.": "Nightly version of Brave with origin repository.",
    "Versão open source despida sem as telemetrias e bloqueios da Google. Nenhuma conta atrelada.": "Open-source version without telemetry and Google blocks.",
    "Virt-Install": "Virt-Install",
    "Virt-Manager": "Virt-Manager",
    "Virt-Viewer": "Virt-Viewer",
    "Virtualização (KVM/QEMU)": "Virtualization (KVM/QEMU)",
    "Virtualização de Sistemas": "System Virtualization",
    "Visualizador de baixissima latência que injeta SPICE e VNC para exibição robusta remota da tela das máquinas virtuais.": "Low latency viewer using SPICE and VNC for VMs.",
    "Visualizador simples interativo baseado em textos (clássico).": "Simple text-based interactive viewer.",
    "Vivaldi": "Vivaldi",
    "Windows Compatibility": "Windows Compatibility",
    "Wine (Multilib)": "Wine (Multilib)",
    "Wrapper otimizadíssimo de WhatsApp Web feito nativamente em C++ WebKit.": "Highly-optimized WhatsApp Web wrapper locally in WebKit.",
    "ZapZap (WhatsApp)": "ZapZap (WhatsApp)",
    "[Checando DNF...]": "[Checking DNF...]",
    "[Checando...]": "[Checking...]",
    "[INSTALADO]": "[INSTALLED]",
    "[NÃO INSTALADO]": "[NOT INSTALLED]",
    "[REINSTALAR]": "[REINSTALL]",
    "↻ Atualizar": "↻ Update",
    "⏳ Interrogando o sistema anfitrião...": "⏳ Interrogating host...",
    "⏳ Rastreador em andamento...": "⏳ Scanning...",
    "⏳ Validando mirrors locais...": "⏳ Validating mirrors...",
    "⏳ Varrendo pacotes KVM Locais...": "⏳ Scanning KVM packages...",
    "⏳ Verificando integridade...": "⏳ Checking integrity...",
    "★ RECOMENDADO MÁQUINA": "★ MACHINE RECOMMENDED",
    "☐ Nenhum": "☐ None",
    "☑ Selecionar Todos": "☑ Select All",
    "☑ Todos": "☑ All",
    "⚠  %1 etapa(s) com erro": "⚠ %1 step(s) with error",
    "⚠️ Construção Concluída: Detectados %1 erro(s). Reveja o Log.": "⚠️ Done: %1 error(s) detected. Review the Log.",
    "✔  0 erros encontrados — Instalação perfeita!": "✔ 0 errors found — Flawless installation!",
    "🏁 Construção Concluída — Nenhuma advertência pendente.": "🏁 Success — No pending warnings.",
    "🐧 Sistema Alvo: Fedora %1   |   👤 Usuário: %2": "🐧 System: Fedora %1   |   👤 User: %2",
    "👁 Esconder Metadados (Modo Compacto)": "👁 Hide Metadata",
    "👁 Exibir Interações (Modo Completo)": "👁 Show Output",
    "📋  Copiar Log Completo": "📋 Copy Full Log",
    "📋  Copiar Log de Erros": "📋 Copy Error Log",
    "🔍 Buscar pacotes (ex: Lutris, Proton)...": "🔍 Search packages...",
    "🔎 Sondando PCI Local em busca de GPUs...": "🔎 Probing PCI for GPUs...",
    "🟢 Aterrisando: ": "🟢 Proceeding: "
}

with open("src/translator.h", "r", encoding="utf-8") as f:
    content = f.read()

# We look for the end of the m_en insertions:
# Let's find the string: "Sem erros."] = "No errors.";
insert_marker = '            m_en["Sem erros."] = "No errors.";'

if insert_marker in content:
    build_str = ""
    for pt, en in translations.items():
        if "Sem erros" in pt or "Rapidora" in pt:
            continue # Already handled or we don't want to break it
        
        # Avoid overriding exact things that are heavily stylized with HTML that might be broken,
        # but my script escapes it anyway.
        
        pt_esc = pt.replace('"', '\\"')
        en_esc = en.replace('"', '\\"')
        # Handle newlines
        pt_esc = pt_esc.replace('\\n', '\\\\n')
        en_esc = en_esc.replace('\\n', '\\\\n')
        
        build_str += f'            m_en["{pt_esc}"] = "{en_esc}";\n'

    new_content = content.replace(insert_marker, insert_marker + "\n\n            // Programmatically generated additional translations\n" + build_str)
    
    with open("src/translator.h", "w", encoding="utf-8") as f:
        f.write(new_content)
        print("Updated translator.h")
else:
    print("Could not find insert marker.")

